#!/usr/bin/env bash

# Check if the number of arguments is less than 4
if [ "$#" -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables for better readability
PATH_TO_FILE=$1
SERVER_IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Use scp to transfer the file to the server's home directory
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$SERVER_IP:~/"

# Check if the scp command was successful
if [ "$?" -eq 0 ]; then
  echo "File transferred successfully."
else
  echo "File transfer failed."
fi
