#!/usr/bin/env bash
# Script that INSTALL AND configure HAPROXY

sudo apt-get -y update

# INSTALL HAPROXY
sudo apt-get install -y haproxy

# The primary configuration file for HAProxy is /etc/haproxy/haproxy.cfg

# Define the IP addresses of your web servers
WEB_SERVERS=("100.26.221.247" "18.209.224.209")

# Backup the original HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Create a new HAProxy configuration file
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg << EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

    # Default ciphers to use on SSL-enabled listening sockets.
    # For more information, see ciphers(1SSL). This list is from:
    #  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
    ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:ECDHE-ECDSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-DSS-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_CCM_SHA256:TLS_AES_128_CCM_8_SHA256
    ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    timeout client 60s
    stats uri /haproxy?stats

    # to config more than one app use this method:
    # acl app1 path_end -i /app1
    # acl app2 path_end -i /app2
    # use_backend app1servers if app1
    # use_backend app2servers if app2
    # define your servers:
    # backend app1servers ...
    # backend app2servers ....

    # to forbid request:
    # http-request deny if { path -i -m beg /admin }


    default_backend http_back

backend http_back
    timeout connect 10s
    timeout server 100s
    balance roundrobin

EOF'

# Add the web servers to the backend section
for SERVER in "${WEB_SERVERS[@]}"; do
    sudo bash -c "echo '    server web_$SERVER $SERVER:80 check' >> /etc/haproxy/haproxy.cfg"
done


# to run haproxy with costum config try:
# haproxy -f file.cfg

# ENABLE THE HAPROXY
sudo systemctl enable haproxy
sudo systemctl start haproxy



# to set the https for haproxy:

# stop any server listing in port 80
#sudo systemctl stop haproxy

# install letsencrypt lib
# sudo apt install letsencrypt

# start the process to get public and private keys
# sudo certbot certonly --standalone
# answere the qustions and then you will get the keys that indecates that this is trusted devise
# they will ask you about your email and the domain of your server


# know you must save the two keys in one file to let haproxy use them you can use this command:
# the paths will apeaer once you complete the last step
# sudo cat pricate/path cerifcate/path | sudo tee /where/you/want/to/save/file.pem
# like:
# sudo cat vim /etc/letsencrypt/live/mobashir.ddns.net/privkey.pem /etc/letsencrypt/live/mobashir.ddns.net/fullchain.pem | sudo tee /etc/ssl/private/cert.pem


# know in the haproxy config file add this to frontendhttpsandsttp
# bind *:443 ssl crt /where/you/want/to/save/file.pem
# like : bind *:443 ssl crt //etc/ssl/private/cert.pem


 # check for synatx erorrs:
 # sudo haproxy -c -f /etc/haproxy/haproxy.cfg
 # sudo systemctl start haproxy
