#!/usr/bin/env bash
# print the hours and minutes of a clock

# Initialize hour and minute variables
hour=0
minute=1

# Display hours from 0 to 12 and minutes from 1 to 59
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    while [ $minute -le 59 ]; do
        echo $minute
        ((minute++))
    done
    ((hour++))
    minute=1
done