#!/usr/bin/env bash
# this script will conect to server using ip and private key in 
# the file ~/.ssh/school


# Define the server IP address or hostname
SERVER="100.26.221.247"

# Connect to the server using the private key and user ubuntu
ssh -i ~/.ssh/school ubuntu@$SERVER
